[package]
name = "merkle-script"
version = "1.1.0"
edition = "2021"
publish = false

[dependencies]
sp1-sdk = { workspace = true }
merkle = { workspace = true }
sp1-util = { workspace = true }

[build-dependencies]
sp1-build = { workspace = true }
