[package]
name = "sp1-util"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true
keywords.workspace = true

[dependencies]
merkle.workspace = true
blake3 = { workspace = true }

[lints]
workspace = true
